#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
    ['hbase_kernel']

package_data = \
    {'': ['*']}

install_requires = \
    ['pexpect>=4.0']

setup(name='hbase_kernel',
      version='0.7.2',
      description='A hbase kernel for Jupyter',
      author='Feng Cunguang',
      author_email='f.cg@qq.com',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      )
